# Snapcraft project file for the R5 DHIS Client software
#
# Copyright 2026 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause
name: dhis-client
title: R5 DHIS Client (UNOFFICIAL)
base: core24
version: '5.5'
summary: Dynamic Host Information System - client
description: |
  dhid is the DHIS client daemon. After setting up with a DHIS provider, each machine may run a dhid daemon (in background) in order to update its dynamic IP address within the server.

  This is NOT an official distribution of the R5 DHIS Client software, please refer to the snap's own issue tracker for support:

  Work items · Unofficial snap packaging for R5 DHIS Client · GitLab
  https://gitlab.com/brlin/dhis-client-snap/-/work_items

website: https://dhis.org
contact: https://gitlab.com/brlin/dhis-client-snap/-/work_items
issues: https://gitlab.com/brlin/dhis-client-snap/-/work_items
source-code: https://gitlab.com/brlin/dhis-client-snap
license: BSD-2-Clause
grade: stable
confinement: strict

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]
  ppc64el:
    build-on: [ppc64el]
    build-for: [ppc64el]
  s390x:
    build-on: [s390x]
    build-for: [s390x]
  riscv64:
    build-on: [riscv64]
    build-for: [riscv64]

parts:
  dhis-client:
    source: dhid-5.5.tar.gz
    # Not supported yet
    # Support download part source from FTP URLs · Issue #1546 · canonical/craft-parts
    # https://github.com/canonical/craft-parts/issues/1546
    #source: ftp://ftp.dhis.org/pub/dhis/dhid-5.5.tar.gz
    plugin: make
    build-packages:
      - gcc
      - libgmp-dev
      - make
    stage-packages:
      - libgmp10
    override-build: |
      make
      install -D dhid "${CRAFT_PART_INSTALL}/usr/local/bin/dhid"
      install -D genkeys "${CRAFT_PART_INSTALL}/usr/local/bin/dhid-genkeys"
      install -Dm644 dhid.conf.sample "${CRAFT_PART_INSTALL}/usr/local/share/dhis-client/dhid.conf.sample"

  local-files:
    source: snap/local
    plugin: dump
    organize:
      dhid-wrapper: usr/local/bin/dhid-wrapper

apps:
  dhis-client:
    command: usr/local/bin/dhid-wrapper
    daemon: forking
    plugs:
      - network
      - network-bind
